<?php

namespace AppBundle\Repository;

/**
 * EvidencijaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvidencijaRepository extends \Doctrine\ORM\EntityRepository
{
}
