<?php

namespace AppBundle\Repository;

/**
 * RazlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RazlogRepository extends \Doctrine\ORM\EntityRepository
{
}
