user_all:
    path:  /users
    defaults: { _controller: AppBundle:Api/Users:all , _format: json }
    requirements:
        _method: GET

user_get:
    path:  /users/{id}
    defaults: { _controller: AppBundle:Api/Users:get , _format: json }
    requirements:
        _method: GET
        id: '\d+'      

user_info:
    path:  /userInfo
    defaults: { _controller: AppBundle:Api/Users:userInfo , _format: json }
    requirements:
        _method: GET
        
user_update_email:
    path:  /userUpdateEmail
    defaults: { _controller: AppBundle:Api/Users:userUpdateEmail , _format: json }
    requirements:
        _method: POST

evidencija_pod:
    path:  /evidencija
    defaults: { _controller: AppBundle:Api/Evidencija:unesipodatke , _format: json }
    requirements:
        _method: POST

evidencija_get:
    path:  /evidencija_dana
    defaults: { _controller: AppBundle:Api/Evidencijadana:evidencija_dana , _format: json }
    requirements:
        _method: GET

evidencija_get_id:
    path:  /evidencija_dana/{id}
    defaults: { _controller: AppBundle:Api/Evidencijadana:get , _format: json }
    requirements:
        _method: GET
        id: '\d+'