<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> masimo
rec_ent_user:
    resource: "@RecENTUserBundle/Resources/config/routing.php"
    prefix:   /

<<<<<<< HEAD
>>>>>>> 42de2340cb8d642fdcc43bea458ef2871aaed8fd
=======
>>>>>>> masimo
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

<<<<<<< HEAD
<<<<<<< HEAD

=======
=======
>>>>>>> masimo
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_rest:
    type:     rest
    prefix:   /api
    resource: "api-routing.yml"

<<<<<<< HEAD
    
>>>>>>> 42de2340cb8d642fdcc43bea458ef2871aaed8fd
=======
    
>>>>>>> masimo
